### ISSUE TITLE
Current OpenCV version do not support SIFT

### ISSUE THREAD

**Issue by Neumi** [alyssaq/3Dreconstruction#8]
Current OpenCV versions do not support SIFT.

`python3 example.py`
 
returns 

`Traceback (most recent call last):
  File "example.py", line 90, in <module>
    points1, points2, intrinsic = dino()
  File "example.py", line 68, in dino
    pts1, pts2 = features.find_correspondence_points(img1, img2)
  File "/content/3Dreconstruction/features.py", line 6, in find_correspondence_points
    sift = cv2.xfeatures2d.SIFT_create()
cv2.error: OpenCV(3.4.3) /io/opencv_contrib/modules/xfeatures2d/src/sift.cpp:1207: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'
`

**Comment by ifhams98** [comment]
Use ORB instead of SIFT and knnmatch insead of flann
